apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasher-helmchart.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "hasher-helmchart.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}

  DB_HOST: {{ include "hasher-helmchart.fullname" . }}-postgresql
  DB_DRIVER: postgres
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword }}
  DB_NAME: {{ .Values.postgresql.auth.database }}
  DB_PORT: "5432"