apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-integrity-sum-config
data:
  {{ .Values.container.name }}: |
      PID_NAME={{ .Values.configMap.processName }}
      MOUNT_PATH={{ .Values.configMap.mountPath }}
