
postgresql:
  auth:
    postgresPassword: ""
    username: ""
    password: ""
    database: ""
    postgresqlDataDir: /bitnami/postgresql/data

  primary:
    initdb:
      scripts:
        00_init_extensions.sh: |
          #!/bin/sh
          export PGPASSWORD=$POSTGRES_PASSWORD 
          psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c "
          CREATE TABLE IF NOT EXISTS hashfiles 
          ( 
          id                BIGSERIAL PRIMARY KEY,
          file_name         VARCHAR NOT NULL,
          full_file_path    TEXT    NOT NULL,
          algorithm         VARCHAR NOT NULL,
          hash_sum          VARCHAR NOT NULL,
          name_deployment   TEXT,
          name_pod          TEXT,
          time_of_creation  VARCHAR (50),
          image_tag         TEXT,
          CONSTRAINT files_unique UNIQUE (full_file_path, algorithm)
          );"

    podSecurityContext:
      enabled: false
      fsGroup: ""
    containerSecurityContext:
      enabled: false
      runAsUser: "auto"

    persistence:
      enabled: true
      existingClaim: ""
      accessModes:
        - ReadWriteMany
      size: 5Gi

    readReplicas:
      podSecurityContext:
        enabled: false
        fsGroup: ""
      containerSecurityContext:
        enabled: false
        runAsUser: "auto"

    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"


serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


